### ISSUE TITLE
Callback not supported

### ISSUE THREAD

**Issue by vipertechofficial** [virtualeconomy/js-v-sdk#40]
How can I use the API trough callbacks ?
![image](https://user-images.githubusercontent.com/74778466/103463809-8aa80180-4d2f-11eb-8e6f-4f8c7b0078ae.png)

In the image I wanted to perform a test to show account balance on login in the console, but it don't work.

![image](https://user-images.githubusercontent.com/74778466/103463913-29ccf900-4d30-11eb-8304-a446902f0b32.png)

Here I got a promise.

![image](https://user-images.githubusercontent.com/74778466/103463971-a069f680-4d30-11eb-8546-e7be8a6e33e8.png)

Here I got nothing.

COULD SOMEONE EXPLAIN ME HOW TO be able to work with the API just like pouchDB ? https://pouchdb.com/api.html

The following code shows nothing in the console.

```
chain.getBalanceDetail(new_account.address).then(response => {
        
        console.log(response);
    }, respError =>{

        console.log(respError);
    });
```

**Comment by vipertechofficial** [comment]
It should be very simple to solve, but well, I am quite over dated in some specific domains.

**Comment by vipertechofficial** [comment]
Does the API works from localhost?

**Comment by Haynar216** [comment]
```
const chain = new Blockchain(NODE_IP, NETWORK_BYTE)
```

Here, testnet node IP `http://test.v.systems:9922` is not working for now. I suggest using `http://marble.vos.systems:9924`

I hope my advice can help you.

**Comment by SheldonYS** [comment]
Currently, we are moving nodes. `marble.vos.systems` could be shutdown recently. Please use the following nodes instead

```
http://vaivora.vos.systems:9924
http://gabija.vos.systems:9924
http://test-node.v.systems:9924
```

You can create chain class like this:
```
const vsys = require("@virtualeconomy/js-v-sdk");
const constants = vsys.constants;
const node_address = "http://vaivora.vos.systems:9924"; // change to your node address
const network_byte = constants.TESTNET_BYTE;
var chain = new vsys.Blockchain(node_address, network_byte);

chain.getBalanceDetail('AUAX5tBz94KmpRdZuaX3FGXBMCQUxgb1hj5').then(response => {
        console.log(response);
    }, respError =>{
        console.log(respError);
    });
```

**Comment by vipertechofficial** [comment]
Ok thanks, I used 
`const node_address = "http://test.v.systems:9922";` I'll close it later, I am currently developing something, I'll check it out in a few hours.
