### ISSUE TITLE
Update node IP

### ISSUE THREAD

**Issue by vipertechofficial** [virtualeconomy/js-v-sdk#42]
https://explorer.v.systems/address/ARJjyYFMixaY7h5xaR8mGT42V9VSRfm5MvJ #WORK
http://test-node.v.systems:9924/addresses/balance/ARJjyYFMixaY7h5xaR8mGT42V9VSRfm5MvJ #DOESNT

What's wrong with it?

EDIT: use -> `"https://wallet.v.systems/api/"`

**Comment by SheldonYS** [comment]
The address "ARJjyYFMixaY7h5xaR8mGT42V9VSRfm5MvJ" is a mainnet address. However, "test-node.v.systems:9924" is a testnet node. We cannot use testnet address in mainnet.
"https://wallet.v.systems/api/" is mainnet node, so it works.
