### ISSUE TITLE
Read transaction attachment 

### ISSUE THREAD

**Issue by vipertechofficial** [virtualeconomy/js-v-sdk#45]
Is it possible to implement a methods to get the clear text of a transactions attachment, I think it uses the public key of the receiver but how could we decrypt this?

**Comment by SheldonYS** [comment]
Just decode with base58. All attachments are shown as base58 format to avoid invisible char showing.

**Comment by Haynar216** [comment]
Here is the sample code
```
import base58 from 'base-58'
import converters from '@/js-v-sdk/src/utils/converters'
let bytes = base58.decode(attachment)
value = converters.byteArrayToString(bytes)
```
